/*
 *  This file is auto generated by oeedger8r. DO NOT EDIT.
 */
#include "enc_u.h"
#include <openenclave/edger8r/host.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>

OE_EXTERNC_BEGIN

/* Wrappers for ecalls */

oe_result_t ecall_TaCreateMasterEncryptionKey(
        oe_enclave_t* enclave,
        int* _retval)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_TaCreateMasterEncryptionKey_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_TaCreateMasterEncryptionKey_args_t));

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_TaCreateMasterEncryptionKey_args_t));

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));


    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_TaCreateMasterEncryptionKey,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    *_retval = _pargs_out->_retval;

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t ecall_TaDestroyMasterEncryptionKey(
        oe_enclave_t* enclave,
        int* _retval)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_TaDestroyMasterEncryptionKey_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_TaDestroyMasterEncryptionKey_args_t));

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_TaDestroyMasterEncryptionKey_args_t));

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));


    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_TaDestroyMasterEncryptionKey,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    *_retval = _pargs_out->_retval;

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t ecall_TaGetRandomBytes(
        oe_enclave_t* enclave,
        int* _retval,
        unsigned char* buffer,
        size_t buffer_size)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_TaGetRandomBytes_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));
    _args.buffer = (unsigned char*) buffer;
    _args.buffer_size = buffer_size;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_TaGetRandomBytes_args_t));

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_TaGetRandomBytes_args_t));
    if (buffer) OE_ADD_SIZE(_output_buffer_size, _args.buffer_size);

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));


    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_TaGetRandomBytes,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    *_retval = _pargs_out->_retval;
    OE_READ_OUT_PARAM(buffer, (size_t)(_args.buffer_size));

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t ecall_TaEncryptData(
        oe_enclave_t* enclave,
        int* _retval,
        const unsigned char* plaintext,
        size_t plaintext_len,
        const unsigned char* aad,
        size_t aad_len,
        const unsigned char* iv,
        size_t iv_len,
        unsigned char* output_buffer,
        size_t output_buffer_size)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_TaEncryptData_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));
    _args.plaintext = (unsigned char*) plaintext;
    _args.plaintext_len = plaintext_len;
    _args.aad = (unsigned char*) aad;
    _args.aad_len = aad_len;
    _args.iv = (unsigned char*) iv;
    _args.iv_len = iv_len;
    _args.output_buffer = (unsigned char*) output_buffer;
    _args.output_buffer_size = output_buffer_size;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_TaEncryptData_args_t));
    if (plaintext) OE_ADD_SIZE(_input_buffer_size, _args.plaintext_len);
    if (aad) OE_ADD_SIZE(_input_buffer_size, _args.aad_len);
    if (iv) OE_ADD_SIZE(_input_buffer_size, _args.iv_len);

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_TaEncryptData_args_t));
    if (output_buffer) OE_ADD_SIZE(_output_buffer_size, _args.output_buffer_size);

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));

    OE_WRITE_IN_PARAM(plaintext, _args.plaintext_len);
    OE_WRITE_IN_PARAM(aad, _args.aad_len);
    OE_WRITE_IN_PARAM(iv, _args.iv_len);

    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_TaEncryptData,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    *_retval = _pargs_out->_retval;
    OE_READ_OUT_PARAM(output_buffer, (size_t)(_args.output_buffer_size));

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t ecall_TaDecryptData(
        oe_enclave_t* enclave,
        int* _retval,
        const unsigned char* ciphertext_buffer,
        size_t ciphertext_buffer_size,
        const unsigned char* aad,
        size_t aad_len,
        const unsigned char* iv,
        size_t iv_len,
        unsigned char* output_buffer,
        size_t output_buffer_size)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_TaDecryptData_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));
    _args.ciphertext_buffer = (unsigned char*) ciphertext_buffer;
    _args.ciphertext_buffer_size = ciphertext_buffer_size;
    _args.aad = (unsigned char*) aad;
    _args.aad_len = aad_len;
    _args.iv = (unsigned char*) iv;
    _args.iv_len = iv_len;
    _args.output_buffer = (unsigned char*) output_buffer;
    _args.output_buffer_size = output_buffer_size;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_TaDecryptData_args_t));
    if (ciphertext_buffer) OE_ADD_SIZE(_input_buffer_size, _args.ciphertext_buffer_size);
    if (aad) OE_ADD_SIZE(_input_buffer_size, _args.aad_len);
    if (iv) OE_ADD_SIZE(_input_buffer_size, _args.iv_len);

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_TaDecryptData_args_t));
    if (output_buffer) OE_ADD_SIZE(_output_buffer_size, _args.output_buffer_size);

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));

    OE_WRITE_IN_PARAM(ciphertext_buffer, _args.ciphertext_buffer_size);
    OE_WRITE_IN_PARAM(aad, _args.aad_len);
    OE_WRITE_IN_PARAM(iv, _args.iv_len);

    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_TaDecryptData,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    *_retval = _pargs_out->_retval;
    OE_READ_OUT_PARAM(output_buffer, (size_t)(_args.output_buffer_size));

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t ecall_TaSetSigningKey(
        oe_enclave_t* enclave,
        int* _retval,
        const unsigned char* key,
        size_t key_len)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_TaSetSigningKey_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));
    _args.key = (unsigned char*) key;
    _args.key_len = key_len;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_TaSetSigningKey_args_t));
    if (key) OE_ADD_SIZE(_input_buffer_size, _args.key_len);

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_TaSetSigningKey_args_t));

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));

    OE_WRITE_IN_PARAM(key, _args.key_len);

    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_TaSetSigningKey,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    *_retval = _pargs_out->_retval;

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t ecall_TaSignData(
        oe_enclave_t* enclave,
        int* _retval,
        const unsigned char* data_to_be_signed,
        size_t data_to_be_signed_size,
        unsigned char* digest,
        size_t digest_size)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_TaSignData_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));
    _args.data_to_be_signed = (unsigned char*) data_to_be_signed;
    _args.data_to_be_signed_size = data_to_be_signed_size;
    _args.digest = (unsigned char*) digest;
    _args.digest_size = digest_size;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_TaSignData_args_t));
    if (data_to_be_signed) OE_ADD_SIZE(_input_buffer_size, _args.data_to_be_signed_size);

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_TaSignData_args_t));
    if (digest) OE_ADD_SIZE(_output_buffer_size, _args.digest_size);

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));

    OE_WRITE_IN_PARAM(data_to_be_signed, _args.data_to_be_signed_size);

    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_TaSignData,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    *_retval = _pargs_out->_retval;
    OE_READ_OUT_PARAM(digest, (size_t)(_args.digest_size));

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t ecall_TaDeriveAndSignData(
        oe_enclave_t* enclave,
        int* _retval,
        const unsigned char* identity,
        size_t identity_size,
        const unsigned char* data_to_be_signed,
        size_t data_to_be_signed_size,
        unsigned char* digest,
        size_t digest_size)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_TaDeriveAndSignData_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));
    _args.identity = (unsigned char*) identity;
    _args.identity_size = identity_size;
    _args.data_to_be_signed = (unsigned char*) data_to_be_signed;
    _args.data_to_be_signed_size = data_to_be_signed_size;
    _args.digest = (unsigned char*) digest;
    _args.digest_size = digest_size;

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_TaDeriveAndSignData_args_t));
    if (identity) OE_ADD_SIZE(_input_buffer_size, _args.identity_size);
    if (data_to_be_signed) OE_ADD_SIZE(_input_buffer_size, _args.data_to_be_signed_size);

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_TaDeriveAndSignData_args_t));
    if (digest) OE_ADD_SIZE(_output_buffer_size, _args.digest_size);

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));

    OE_WRITE_IN_PARAM(identity, _args.identity_size);
    OE_WRITE_IN_PARAM(data_to_be_signed, _args.data_to_be_signed_size);

    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_TaDeriveAndSignData,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */
    *_retval = _pargs_out->_retval;
    OE_READ_OUT_PARAM(digest, (size_t)(_args.digest_size));

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}



oe_result_t ecall_InitializeStdio(
        oe_enclave_t* enclave)
{
    oe_result_t _result = OE_FAILURE;

    /* Marshaling struct */ 
    ecall_InitializeStdio_args_t _args, *_pargs_in = NULL, *_pargs_out=NULL;

    /* Marshaling buffer and sizes */ 
    size_t _input_buffer_size = 0;
    size_t _output_buffer_size = 0;
    size_t _total_buffer_size = 0;
    uint8_t* _buffer = NULL;
    uint8_t* _input_buffer = NULL;
    uint8_t* _output_buffer = NULL;
    size_t _input_buffer_offset = 0;
    size_t _output_buffer_offset = 0;
    size_t _output_bytes_written = 0;

    /* Fill marshaling struct */
    memset(&_args, 0, sizeof(_args));

    /* Compute input buffer size. Include in and in-out parameters. */
    OE_ADD_SIZE(_input_buffer_size, sizeof(ecall_InitializeStdio_args_t));

    /* Compute output buffer size. Include out and in-out parameters. */
    OE_ADD_SIZE(_output_buffer_size, sizeof(ecall_InitializeStdio_args_t));

    /* Allocate marshaling buffer */
    _total_buffer_size = _input_buffer_size;
    OE_ADD_SIZE(_total_buffer_size, _output_buffer_size);

    _buffer = (uint8_t*) malloc(_total_buffer_size);
    _input_buffer = _buffer;
    _output_buffer = _buffer + _input_buffer_size;
    if (_buffer == NULL) { 
        _result = OE_OUT_OF_MEMORY;
        goto done;
    }

    /* Serialize buffer inputs (in and in-out parameters) */
    *(uint8_t**)&_pargs_in = _input_buffer; 
    OE_ADD_SIZE(_input_buffer_offset, sizeof(*_pargs_in));


    /* Copy args structure (now filled) to input buffer */
    memcpy(_pargs_in, &_args, sizeof(*_pargs_in));

    /* Call enclave function */
    if((_result = oe_call_enclave_function(
                        enclave,
                        fcn_id_ecall_InitializeStdio,
                        _input_buffer, _input_buffer_size,
                        _output_buffer, _output_buffer_size,
                         &_output_bytes_written)) != OE_OK)
        goto done;

    /* Set up output arg struct pointer*/
    *(uint8_t**)&_pargs_out = _output_buffer; 
    OE_ADD_SIZE(_output_buffer_offset, sizeof(*_pargs_out));

    /* Check if the call succeeded */
    if ((_result=_pargs_out->_result) != OE_OK)
        goto done;

    /* Currently exactly _output_buffer_size bytes must be written */
    if (_output_bytes_written != _output_buffer_size) {
        _result = OE_FAILURE;
        goto done;
    }

    /* Unmarshal return value and out, in-out parameters */

    _result = OE_OK;
done:    
    if (_buffer)
        free(_buffer);
    return _result;
}




/* ocall functions */

void ocall_ocall_mkdir(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_mkdir_args_t* pargs_in = (ocall_mkdir_args_t*) input_buffer;
    ocall_mkdir_args_t* pargs_out = (ocall_mkdir_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(dirname, pargs_in->dirname_len * sizeof(char));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_mkdir(
        (const char*) pargs_in->dirname);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_GetUntrustedFileSize(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_GetUntrustedFileSize_args_t* pargs_in = (ocall_GetUntrustedFileSize_args_t*) input_buffer;
    ocall_GetUntrustedFileSize_args_t* pargs_out = (ocall_GetUntrustedFileSize_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(filename, pargs_in->filename_len * sizeof(char));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_GetUntrustedFileSize(
        (const char*) pargs_in->filename);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_GetUntrustedFileContent(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_GetUntrustedFileContent_args_t* pargs_in = (ocall_GetUntrustedFileContent_args_t*) input_buffer;
    ocall_GetUntrustedFileContent_args_t* pargs_out = (ocall_GetUntrustedFileContent_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(location, pargs_in->location_len * sizeof(char));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_GetUntrustedFileContent(
        (const char*) pargs_in->location,
        pargs_in->len);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_ExportFile(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_ExportFile_args_t* pargs_in = (ocall_ExportFile_args_t*) input_buffer;
    ocall_ExportFile_args_t* pargs_out = (ocall_ExportFile_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(filename, pargs_in->filename_len * sizeof(char));
    OE_SET_IN_POINTER(content, pargs_in->len);

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_ExportFile(
        (const char*) pargs_in->filename,
        pargs_in->appendToExistingFile,
        (const void*) pargs_in->content,
        pargs_in->len);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_ExportPublicCertificate(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_ExportPublicCertificate_args_t* pargs_in = (ocall_ExportPublicCertificate_args_t*) input_buffer;
    ocall_ExportPublicCertificate_args_t* pargs_out = (ocall_ExportPublicCertificate_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(location, pargs_in->location_len * sizeof(char));
    OE_SET_IN_POINTER(ptr, pargs_in->len);

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_ExportPublicCertificate(
        (const char*) pargs_in->location,
        (const void*) pargs_in->ptr,
        pargs_in->len);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_stat64i32(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_stat64i32_args_t* pargs_in = (ocall_stat64i32_args_t*) input_buffer;
    ocall_stat64i32_args_t* pargs_out = (ocall_stat64i32_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(path, pargs_in->path_len * sizeof(char));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */
    OE_SET_OUT_POINTER(buf, sizeof(struct ocall_struct_stat64i32));

    /* Call user function */
    pargs_out->_retval = ocall_stat64i32(
        (const char*) pargs_in->path,
        pargs_in->buf);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_remove(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_remove_args_t* pargs_in = (ocall_remove_args_t*) input_buffer;
    ocall_remove_args_t* pargs_out = (ocall_remove_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(filename, pargs_in->filename_len * sizeof(char));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_remove(
        (const char*) pargs_in->filename);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_opendir(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_opendir_args_t* pargs_in = (ocall_opendir_args_t*) input_buffer;
    ocall_opendir_args_t* pargs_out = (ocall_opendir_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */
    OE_SET_IN_POINTER(filePathWithWildcards, pargs_in->filePathWithWildcards_len * sizeof(char));

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_opendir(
        (const char*) pargs_in->filePathWithWildcards,
        pargs_in->matchingFileNameSize);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_readdir(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_readdir_args_t* pargs_in = (ocall_readdir_args_t*) input_buffer;
    ocall_readdir_args_t* pargs_out = (ocall_readdir_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_readdir(
        pargs_in->findNextHandle,
        pargs_in->matchingFileNameSize);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}

void ocall_ocall_closedir(
        uint8_t* input_buffer, size_t input_buffer_size,
        uint8_t* output_buffer, size_t output_buffer_size,
        size_t* output_bytes_written)
{
    oe_result_t _result = OE_FAILURE;

    /* Prepare parameters */
    ocall_closedir_args_t* pargs_in = (ocall_closedir_args_t*) input_buffer;
    ocall_closedir_args_t* pargs_out = (ocall_closedir_args_t*) output_buffer;

    size_t input_buffer_offset = 0;
    size_t output_buffer_offset = 0;
    OE_ADD_SIZE(input_buffer_offset, sizeof(*pargs_in));
    OE_ADD_SIZE(output_buffer_offset, sizeof(*pargs_out));

    /* Make sure input and output buffers are valid */
    if (!input_buffer || !output_buffer) {
        _result = OE_INVALID_PARAMETER;
        goto done;

    }
    /* Set in and in-out pointers */

    /* Set out and in-out pointers. In-out parameters are copied to output buffer. */

    /* Call user function */
    pargs_out->_retval = ocall_closedir(
        pargs_in->findNextHandle);

    /* Success. */
    _result = OE_OK; 
    *output_bytes_written = output_buffer_offset;

done:
    if (pargs_out && output_buffer_size >= sizeof(*pargs_out)) 
        pargs_out->_result = _result;
}


/*ocall function table*/
static oe_ocall_func_t __enc_ocall_function_table[]= {
    (oe_ocall_func_t) ocall_ocall_mkdir,
    (oe_ocall_func_t) ocall_ocall_GetUntrustedFileSize,
    (oe_ocall_func_t) ocall_ocall_GetUntrustedFileContent,
    (oe_ocall_func_t) ocall_ocall_ExportFile,
    (oe_ocall_func_t) ocall_ocall_ExportPublicCertificate,
    (oe_ocall_func_t) ocall_ocall_stat64i32,
    (oe_ocall_func_t) ocall_ocall_remove,
    (oe_ocall_func_t) ocall_ocall_opendir,
    (oe_ocall_func_t) ocall_ocall_readdir,
    (oe_ocall_func_t) ocall_ocall_closedir,
    NULL
};

oe_result_t oe_create_enc_enclave(const char* path,
                                 oe_enclave_type_t type,
                                 uint32_t flags,
                                 const void* config,
                                 uint32_t config_size,
                                 oe_enclave_t** enclave)
{
    return oe_create_enclave(path,
               type,
               flags,
               config,
               config_size,
               __enc_ocall_function_table,
               10,
               enclave);
}

OE_EXTERNC_END
